### ISSUE TITLE
Support for gradle 9.1.0 and java 25 build

### ISSUE THREAD

**Issue by fugerit79** [fugerit-org/freemarker#3]
On 16th of September 2025 [java 25](https://docs.oracle.com/en-us/iaas/releasenotes/java-management/jdk-25-release-note.htm) has been release (latest LTS afer java 21).

A few days later gradle added supporto for it on gradle [9.1.0](https://docs.gradle.org/current/userguide/compatibility.html).

but trying to build [Apache FreeMarker](https://github.com/apache/freemarker/) on gradle 9.1.0 leads to the following error : 

```txt
> Task :buildSrc:compileKotlin FAILED
e: file:///omnia/workspace/git/fork/freemarker/buildSrc/src/main/kotlin/freemarker/build/CompileJavaccTask.kt:123:68 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type '@Nullable() RelativePath?'.
e: file:///omnia/workspace/git/fork/freemarker/buildSrc/src/main/kotlin/freemarker/build/JakartaSourceRootGeneratorTask.kt:106:58 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type '@Nullable() RelativePath?'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

I see this is not a big issue, as the maven wrapper will select the proper gradle version for me, but I'd like FreeMarker build to work on gradle 9.1.0 too.
